In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("regular_season_totals_2010_2024.csv")
df.head(5)

,SEASON_YEAR,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,AVAILABLE_FLAG
0,2022-23,1610612744,GSW,Golden State Warriors,22201230,2023-04-09T00:00:00,GSW @ POR,W,48.0,58,...,1,1578,55,512,457,678,2455,3,1,1.0
1,2020-21,1610612749,MIL,Milwaukee Bucks,22000051,2020-12-29T00:00:00,MIL @ MIA,W,48.0,51,...,146,1636,33,1830,1361,1552,1220,14,7,1.0
2,2013-14,1610612751,BKN,Brooklyn Nets,21300359,2013-12-16T00:00:00,BKN vs. PHI,W,48.0,47,...,22,2280,406,1979,1,1004,453,19,12,1.0
3,2013-14,1610612757,POR,Portland Trail Blazers,21300347,2013-12-14T00:00:00,POR @ PHI,W,48.0,52,...,2,2065,628,204,1269,272,2190,4,15,1.0
4,2018-19,1610612745,HOU,Houston Rockets,21801200,2019-04-07T00:00:00,HOU vs. PHX,W,48.0,53,...,84,176,149,917,1,244,1725,4,20,1.0

In [3]:
df.shape

(33316, 57)

In [5]:
fechaSeleccionada = df[df["SEASON_YEAR"] == "2022-23"]
fechaSeleccionada

,SEASON_YEAR,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,AVAILABLE_FLAG
0,2022-23,1610612744,GSW,Golden State Warriors,22201230,2023-04-09T00:00:00,GSW @ POR,W,48.0,58,...,1,1578,55,512,457,678,2455,3,1,1.0
13,2022-23,1610612738,BOS,Boston Celtics,22200135,2022-11-05T00:00:00,BOS @ NYK,W,48.0,47,...,356,882,1735,2005,859,463,2257,152,300,1.0
39,2022-23,1610612738,BOS,Boston Celtics,22200772,2023-02-01T00:00:00,BOS vs. BKN,W,48.0,53,...,605,665,2048,1183,52,74,2388,53,5,1.0
45,2022-23,1610612744,GSW,Golden State Warriors,22200814,2023-02-06T00:00:00,GSW vs. OKC,W,48.0,56,...,3,1578,1444,1603,457,463,2443,37,62,1.0
47,2022-23,1610612749,MIL,Milwaukee Bucks,22200939,2023-03-01T00:00:00,MIL vs. ORL,W,48.0,49,...,474,94,2048,2279,1279,1831,1536,53,123,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33284,2022-23,1610612765,DET,Detroit Pistons,22200919,2023-02-27T00:00:00,DET @ CHA,L,48.0,42,...,2275,179,107,1603,457,678,631,1853,1929,1.0
33285,2022-23,1610612745,HOU,Houston Rockets,22200441,2022-12-17T00:00:00,HOU vs. POR,L,48.0,36,...,2182,1797,1116,512,859,678,1079,2331,1993,1.0
33286,2022-23,1610612745,HOU,Houston Rockets,22200342,2022-12-03T00:00:00,HOU @ GSW,L,48.0,40,...,2338,1368,1444,1183,1279,127,321,2128,2241,1.0
33311,2022-23,1610612766,CHA,Charlotte Hornets,22200710,2023-01-23T00:00:00,CHA @ UTA,L,48.0,38,...,1756,1368,800,294,859,1831,139,2077,2211,1.0
33312,2022-23,1610612746,LAC,LA Clippers,22200754,2023-01-29T00:00:00,LAC @ CLE,L,48.0,37,...,2338,1368,1444,2410,1950,926,460,2220,2339,1.0

In [6]:
fechaSeleccionada.shape

(2460, 57)

In [7]:
fechaSeleccionada.to_csv("regular_season_totals_2010_2024_sql.csv")